health-bar:
  bar-length: 10
  decay-delay-ticks: 60
  display-interval-ticks: 2

barbarian-system:
  building-hp:
    townhall: 300
    cannon: 150
    archer_tower: 120
    gold_mine: 80
    elixir_collector: 80
    wall: 50
  barbarian-damage: 10
  attack-interval-ticks: 20
