name: ClashVillages
version: 1.0.5
main: io.lossai.clash.ClashPlugin
api-version: '1.21'
author: lossai
softdepend: [Citizens, packetevents]
commands:
  clash:
    description: Clash villages main command
    usage: /clash
    aliases: [coc]
  barbarian:
    description: Deploy or clear barbarian NPCs
    usage: /barbarian <deploy <count>|clear>
    permission: clash.admin
permissions:
  clash.admin:
    description: Allows managing other players in future expansions
    default: op